import { Lexend } from 'next/font/google';
import Navbar from "@/app/components/layout/Navbar";
import Hero from "@/app/components/home/Hero";
import Stats from "@/app/components/home/Stats";
import BeatsStore from "@/app/components/home/BeatsStore";
import Sample from "@/app/components/home/Sample"
import './globals.css';

// Configure the font
const lexend = Lexend({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
});

export const metadata = {
  title: "Perlz Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} dark`}
      >
        <Navbar />
        <Hero />
        <Stats />
        <BeatsStore />
        <Sample />
        {children}
      </body>
    </html>
  );
}
