// import { Lexend } from 'next/font/google';
// import Navbar from "@/app/components/layout/Navbar";
// import Hero from "@/app/components/home/Hero";
// import Stats from "@/app/components/home/Stats";
// import About from "@/app/components/home/About";
// import Footer from '@/app/components/layout/Footer'
// import BeatsStore from "@/app/components/home/BeatsStore";
// import Sample from "@/app/components/home/Sample";
// import Services from "@/app/components/home/Services"
// import './globals.css';

// // Configure the font
// const lexend = Lexend({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-lexend',
// });

// export const metadata = {
//   title: "Perlz Portfolio App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({children}) {
//   return (
//     <html lang="en">
//       <body
//         className={`${lexend.variable} dark`}
//       >
//         <Navbar />
//         <Hero />
//         <Stats />
//         <About />
//         <Services />
//         <Sample />
//         <BeatsStore />
//         <Footer />
//         {children}
//       </body>
//     </html>
//   );
// }

import { Lexend } from "next/font/google";
import "./globals.css";

const lexend = Lexend({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend",
});

export const metadata = {
  title: "Perlz — Music Producer",
  description:
    "Crafting the future of sound. Afrobeats, UK tunes, and Hip-Hop production from Lagos.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} dark`}>{children}</body>
    </html>
  );
}
